#!/usr/bin/env python3
"""Closed-loop inverse-dynamics replay of a recorded hand_realtime episode.

Adjacent source poses are treated as samples separated by ``--dt``.  Only the
initial poses/cameras are restored.  Every later pose is produced by a fixed
UE resume/pause pulse and commands computed from the *current replay state*.

This is deliberately a dynamics-feasibility experiment, not an evaluation
policy: it exposes where a recorded transition cannot be generated by the
available BP command space and the calibrated drone first-order response.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import os
import random
import sys
import time
from pathlib import Path
from typing import Any

import cv2
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
for _path in (REPO_ROOT, REPO_ROOT / "unrealzoo-gym", REPO_ROOT / "unrealzoo-gym/example/DataRecording"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))


def _argv_value(name: str, default: str) -> str:
    prefix = f"{name}="
    for i, value in enumerate(sys.argv):
        if value == name and i + 1 < len(sys.argv):
            return sys.argv[i + 1]
        if value.startswith(prefix):
            return value[len(prefix):]
    return default


# Registration and UE launch consume this at import time.
os.environ.setdefault("UNREALZOO_FIXED_TIMESTEP", _argv_value("--dt", "0.1"))

from tools.history.replay_hand_step_base_velocity import (  # noqa: E402
    UNREAL_UNITS_PER_METER,
    fixed_step,
    next_or_after,
    pose_error_m,
    refresh_poses,
    valid_pose,
    wrap_deg,
    yaw_error_deg,
    write_video_frame,
)
from tools.history.replay_unrealzoo_recording import (  # noqa: E402
    build_env_args,
    classify_coop_agents,
    dog_args,
    drone_args,
    make_env,
    maybe_set_drone_yaw,
    read_json,
    reset_env,
    restore_pose,
    set_drone_camera,
    set_ground_yaw,
    set_robotdog_camera,
    write_json,
)
from generate_aerial_ground_human_tracking_small import (  # noqa: E402
    capture_color_mask_snapshot,
    get_global_frame,
)
from generate_robotdog_human_tracking_small import object_mask_ratio_and_bbox  # noqa: E402


def capture_color_mask_snapshot_stable(
    env,
    include_masks: bool,
    attempts: int = 8,
    mode: str = "sequential",
    render_sync_s: float = 0.0,
) -> tuple[np.ndarray, list[np.ndarray | None]]:
    """Capture a complete observation with bounded retries.

    ``batch`` retains the old, faster single UnrealCV request.  ``sequential``
    deliberately uses one request per pose/image.  The latter avoids the UE
    5.6/UnrealCV failure mode where a large mixed batch disconnects the socket
    and the legacy decoder silently returns a truncated response list.
    """
    last_error: Exception | None = None
    for attempt in range(1, max(1, int(attempts)) + 1):
        try:
            if mode == "batch":
                observation, masks = capture_color_mask_snapshot(env, include_masks=include_masks)
            else:
                observation, masks = capture_color_mask_snapshot_sequential(
                    env, include_masks=include_masks, render_sync_s=render_sync_s
                )
            required = [idx for idx, cam_id in enumerate(env.unwrapped.cam_list) if cam_id is not None and cam_id >= 0]
            if required and len(observation) <= max(required):
                raise RuntimeError(
                    f"incomplete RGB batch: got={len(observation)} required_camera_index={max(required)}"
                )
            if include_masks:
                missing_masks = [idx for idx in required if idx >= len(masks) or masks[idx] is None]
                if missing_masks:
                    raise RuntimeError(f"incomplete exact-mask snapshot for agent indices {missing_masks}")
            return observation, masks
        except Exception as exc:
            last_error = exc
            if attempt >= max(1, int(attempts)):
                break
            print(
                f"[snapshot] transient UnrealCV failure attempt={attempt}/{attempts}: {exc}; retrying",
                flush=True,
            )
            time.sleep(0.25 * attempt)
    raise RuntimeError(f"UnrealCV snapshot failed after {attempts} attempts") from last_error


def capture_color_mask_snapshot_sequential(
    env,
    include_masks: bool,
    render_sync_s: float = 0.0,
) -> tuple[np.ndarray, list[np.ndarray | None]]:
    """Stable alternative to ``get_pose_img_batch``.

    Do not use the convenience ``get_obj_*`` helpers here: they retry a
    disconnected socket forever.  A failed request must propagate to the
    bounded snapshot retry / episode watchdog, so a bad UE instance cannot
    stall the resumable batch forever.
    """
    unwrapped = env.unwrapped
    unrealcv = unwrapped.unrealcv

    def request(command: str, decoder, label: str):
        response = unrealcv.client.request(command)
        if response is None:
            raise RuntimeError(f"no UnrealCV response for {label}")
        try:
            return decoder(response)
        except Exception as exc:
            raise RuntimeError(f"invalid UnrealCV response for {label}: {exc}") from exc

    obj_poses: list[list[float]] = []
    for object_name in unwrapped.player_list:
        location = request(
            f"vget /object/{object_name}/location",
            unrealcv.decoder.string2floats,
            f"object location {object_name}",
        )
        rotation = request(
            f"vget /object/{object_name}/rotation",
            unrealcv.decoder.string2floats,
            f"object rotation {object_name}",
        )
        if len(location) < 3 or len(rotation) < 3:
            raise RuntimeError(f"incomplete pose for {object_name}: location={location}, rotation={rotation}")
        obj_poses.append(location + rotation)

    images: list[np.ndarray] = []
    mask_by_agent: list[np.ndarray | None] = [None] * len(unwrapped.cam_list)
    for agent_idx, cam_id in enumerate(unwrapped.cam_list):
        if cam_id is None or cam_id < 0:
            images.append(np.zeros((unwrapped.resolution[1], unwrapped.resolution[0], 3), dtype=np.uint8))
            continue
        color = request(
            f"vget /camera/{cam_id}/lit bmp",
            lambda payload: unrealcv.decoder.decode_img(payload, "bmp"),
            f"camera {cam_id} RGB",
        )
        if render_sync_s > 0:
            time.sleep(render_sync_s)
        if not isinstance(color, np.ndarray) or color.ndim != 3:
            raise RuntimeError(f"invalid RGB image for camera {cam_id}")
        images.append(color)
        if include_masks:
            mask = request(
                f"vget /camera/{cam_id}/object_mask png",
                lambda payload: unrealcv.decoder.decode_img(payload, "png"),
                f"camera {cam_id} mask",
            )
            if render_sync_s > 0:
                time.sleep(render_sync_s)
            if not isinstance(mask, np.ndarray) or mask.ndim < 2:
                raise RuntimeError(f"invalid mask image for camera {cam_id}")
            mask_by_agent[agent_idx] = mask

    observation = np.asarray(images)
    unwrapped.obj_poses = obj_poses
    unwrapped.img_show = unwrapped.prepare_img2show(unwrapped.protagonist_id, observation)
    return observation, mask_by_agent


def body_xy_velocity(before: list[float], after: list[float], dt: float) -> np.ndarray:
    """Measured local [forward, right] velocity in m/s."""
    world = (np.asarray(after[:2], dtype=float) - np.asarray(before[:2], dtype=float)) / UNREAL_UNITS_PER_METER
    yaw = math.radians(float(before[4]))
    return np.asarray(
        [math.cos(yaw) * world[0] + math.sin(yaw) * world[1], -math.sin(yaw) * world[0] + math.cos(yaw) * world[1]],
        dtype=float,
    ) / max(float(dt), 1e-6)


def reference_velocity(actual: list[float], reference: list[float], dt: float) -> np.ndarray:
    return body_xy_velocity(actual, reference, dt)


def body_velocity_between(start: list[float], end: list[float], body_yaw_deg: float, dt: float) -> np.ndarray:
    """Reference XY velocity expressed in an explicitly chosen body frame."""
    world = (np.asarray(end[:2], dtype=float) - np.asarray(start[:2], dtype=float)) / UNREAL_UNITS_PER_METER
    yaw = math.radians(float(body_yaw_deg))
    return np.asarray(
        [math.cos(yaw) * world[0] + math.sin(yaw) * world[1], -math.sin(yaw) * world[0] + math.cos(yaw) * world[1]],
        dtype=float,
    ) / max(float(dt), 1e-6)


def realized_base_velocity(before: list[float], after: list[float], dt: float) -> list[float]:
    """Actual [forward, right, yaw_rate] produced by one fixed UE step."""
    xy = body_xy_velocity(before, after, dt)
    yaw_rate = math.radians(wrap_deg(float(after[4]) - float(before[4]))) / max(float(dt), 1e-6)
    return [float(xy[0]), float(xy[1]), float(yaw_rate)]


def local_waypoints(poses_after_action: list[list[float]], start_index: int, horizon: int) -> tuple[list[list[float]], list[int]]:
    """Future replay poses relative to the current after-action pose.

    These are saved as an auditable geometric label. The training builder still
    derives its own labels from ``base_velocity`` so its existing contract is
    unchanged.
    """
    origin = poses_after_action[start_index]
    yaw0 = math.radians(float(origin[4]))
    points: list[list[float]] = [[0.0, 0.0, 0.0]]
    valid: list[int] = [1]
    for offset in range(1, horizon + 1):
        idx = start_index + offset
        if idx >= len(poses_after_action):
            points.append(points[-1].copy())
            valid.append(0)
            continue
        pose = poses_after_action[idx]
        dx = (float(pose[0]) - float(origin[0])) / UNREAL_UNITS_PER_METER
        dy = (float(pose[1]) - float(origin[1])) / UNREAL_UNITS_PER_METER
        points.append([
            float(math.cos(yaw0) * dx + math.sin(yaw0) * dy),
            float(-math.sin(yaw0) * dx + math.cos(yaw0) * dy),
            float(math.radians(wrap_deg(float(pose[4]) - float(origin[4])))),
        ])
        valid.append(1)
    return points, valid


def clamp(value: float, limit: float) -> tuple[float, bool]:
    limit = max(0.0, float(limit))
    result = float(np.clip(float(value), -limit, limit))
    return result, abs(result - float(value)) > 1e-9


class AdaptiveGroundSpeedModel:
    """Online scalar model for the delayed ground forward-speed actuator."""

    def __init__(self) -> None:
        self.theta = np.asarray([0.0, 1.0, 0.0], dtype=float)  # [a, b, c]
        self.covariance = np.diag([4.0, 2.0, 1.0]).astype(float)
        self.previous_velocity: float | None = None
        self.previous_command: float | None = None
        self.samples = 0

    def update(self, velocity: float) -> None:
        if self.previous_velocity is not None and self.previous_command is not None:
            phi = np.asarray([self.previous_velocity, self.previous_command, 1.0], dtype=float)
            denom = 1.0 + float(phi @ self.covariance @ phi)
            gain = (self.covariance @ phi) / max(denom, 1e-8)
            residual = float(velocity - phi @ self.theta)
            self.theta = self.theta + gain * residual
            self.theta[0] = float(np.clip(self.theta[0], 0.0, 0.95))
            self.theta[1] = float(np.clip(self.theta[1], 0.10, 1.50))
            self.theta[2] = float(np.clip(self.theta[2], -0.40, 0.40))
            self.covariance = (np.eye(3) - np.outer(gain, phi)) @ self.covariance
            self.samples += 1
        self.previous_velocity = float(velocity)

    def inverse_command(self, desired_next_velocity: float, current_velocity: float) -> float:
        a, b, c = [float(value) for value in self.theta]
        return float((desired_next_velocity - a * current_velocity - c) / max(b, 0.10))

    def set_command(self, command: float) -> None:
        self.previous_command = float(command)


def ground_control(
    actual: list[float], reference_before: list[float], reference_after: list[float], reference_after_next: list[float],
    dt: float, yaw_gain: float, max_speed: float, max_turn: float, translation_delay_steps: int,
    feedback_time_s: float, control_mode: str, vector_min_speed_mps: float,
    vector_max_heading_delta_deg: float, reference_lookahead: list[float], reverse_mode: bool,
    reverse_enter_deg: float, reverse_exit_deg: float, heading_goal_deg: float | None,
    heading_goal_rate_deg: float, turn_slowdown_floor: float, heading_deadband_deg: float,
    max_forward_feedback_mps: float, speed_model: str, adaptive_speed_model: AdaptiveGroundSpeedModel | None,
    current_forward_velocity: float,
) -> tuple[list[float], dict[str, Any]]:
    if translation_delay_steps == 0:
        source_velocity = body_velocity_between(reference_before, reference_after, float(actual[4]), dt)
    else:
        # Empirically, ground ``speed`` sent at t controls the translation at
        # t+1, while turn is applied in t.  Preview the source's next pose
        # transition rather than asking an already-sent command to fix t.
        source_velocity = body_velocity_between(reference_after, reference_after_next, float(actual[4]), dt)
    raw_position_feedback = body_velocity_between(
        actual,
        reference_before,
        float(actual[4]),
        max(float(feedback_time_s), dt),
    )
    position_feedback = raw_position_feedback.copy()
    position_feedback[0] = float(np.clip(
        position_feedback[0],
        -float(max_forward_feedback_mps),
        float(max_forward_feedback_mps),
    ))
    desired_body = source_velocity + position_feedback
    source_yaw_delta = wrap_deg(float(reference_after[4]) - float(actual[4]))
    if control_mode == "source_yaw":
        if speed_model == "adaptive_inverse":
            if adaptive_speed_model is None:
                raise RuntimeError("adaptive ground speed model is unavailable")
            speed_target = adaptive_speed_model.inverse_command(
                float(desired_body[0]), current_forward_velocity
            )
        else:
            speed_target = float(desired_body[0])
        yaw_delta = source_yaw_delta
    elif control_mode in {"vector_2d", "vector_2d_stable", "vector_2d_lookahead", "vector_2d_damped"}:
        # The ground BP is still a unicycle: it has no lateral actuator.  We
        # approximate a 2D velocity command by steering toward the requested
        # body-vector direction and using its magnitude as forward speed.
        vector_norm = float(np.linalg.norm(desired_body))
        vector_yaw_delta = math.degrees(math.atan2(float(desired_body[1]), float(desired_body[0])))
        if control_mode == "vector_2d":
            speed_target = vector_norm
            yaw_delta = vector_yaw_delta
        elif control_mode == "vector_2d_stable" and vector_norm < float(vector_min_speed_mps):
            # A nearly-zero vector has no reliable direction. Preserve source
            # heading and avoid a heading flip caused by atan2(very small y,x).
            speed_target = float(desired_body[0])
            yaw_delta = source_yaw_delta
        elif control_mode == "vector_2d_stable":
            # A unicycle can realize a behind-vector by reversing, without a
            # 180-degree heading flip. Keep the heading correction bounded so
            # feedback noise cannot create alternating full-rate turns.
            speed_target = vector_norm
            yaw_delta = vector_yaw_delta
            if yaw_delta > 90.0:
                yaw_delta -= 180.0
                speed_target = -speed_target
            elif yaw_delta < -90.0:
                yaw_delta += 180.0
                speed_target = -speed_target
            yaw_delta = float(np.clip(yaw_delta, -vector_max_heading_delta_deg, vector_max_heading_delta_deg))
        else:
            # Heading is derived from a spatial lookahead, not from the
            # frame-to-frame feedback vector. This removes atan2 direction
            # chatter when lateral feedback crosses zero.
            lookahead_body = body_velocity_between(
                actual,
                reference_lookahead,
                float(actual[4]),
                1.0,
            )
            lookahead_distance = float(np.linalg.norm(lookahead_body))
            raw_heading_delta = math.degrees(
                math.atan2(float(lookahead_body[1]), float(lookahead_body[0]))
            ) if lookahead_distance >= float(vector_min_speed_mps) else source_yaw_delta
            abs_raw = abs(raw_heading_delta)
            if reverse_mode:
                next_reverse_mode = abs_raw >= float(reverse_exit_deg)
            else:
                next_reverse_mode = abs_raw > float(reverse_enter_deg)
            if next_reverse_mode:
                raw_heading_delta = wrap_deg(raw_heading_delta - 180.0)
                speed_target = -vector_norm
            else:
                speed_target = vector_norm
            desired_heading_goal = float(actual[4] + raw_heading_delta)
            if control_mode == "vector_2d_damped":
                if heading_goal_deg is None:
                    next_heading_goal = float(actual[4])
                else:
                    next_heading_goal = float(
                        heading_goal_deg
                        + np.clip(
                            wrap_deg(desired_heading_goal - heading_goal_deg),
                            -heading_goal_rate_deg,
                            heading_goal_rate_deg,
                        )
                    )
                yaw_delta = wrap_deg(next_heading_goal - float(actual[4]))
                # Brake while turning. Sending full delayed speed into a large
                # heading correction is the source of the ground oscillation.
                speed_target *= max(
                    float(turn_slowdown_floor),
                    math.cos(math.radians(abs(yaw_delta))),
                )
            else:
                next_heading_goal = desired_heading_goal
                yaw_delta = raw_heading_delta
            yaw_delta = float(np.clip(yaw_delta, -vector_max_heading_delta_deg, vector_max_heading_delta_deg))
            if control_mode == "vector_2d_damped" and abs(yaw_delta) < float(heading_deadband_deg):
                yaw_delta = 0.0
    else:
        raise ValueError(f"unsupported ground control mode: {control_mode}")
    speed, speed_sat = clamp(speed_target, max_speed)
    unconstrained_turn = yaw_delta / max(float(yaw_gain), 1e-9)
    turn, turn_sat = clamp(unconstrained_turn, max_turn)
    return [turn, speed * UNREAL_UNITS_PER_METER], {
        "translation_delay_steps": int(translation_delay_steps),
        "control_mode": control_mode,
        "source_preview_body_velocity_mps": source_velocity.tolist(),
        "raw_position_feedback_body_velocity_mps": raw_position_feedback.tolist(),
        "position_feedback_body_velocity_mps": position_feedback.tolist(),
        "desired_body_velocity_mps": desired_body.tolist(),
        "unexecutable_lateral_velocity_mps": float(desired_body[1]),
        "source_yaw_delta_deg": source_yaw_delta,
        "vector_yaw_delta_deg": vector_yaw_delta if control_mode in {"vector_2d", "vector_2d_stable"} else None,
        "command_yaw_delta_deg": yaw_delta,
        "lookahead_heading_distance_m": (
            lookahead_distance if control_mode == "vector_2d_lookahead" else None
        ),
        "reverse_mode": bool(next_reverse_mode) if control_mode in {"vector_2d_lookahead", "vector_2d_damped"} else False,
        "heading_goal_deg": (
            next_heading_goal if control_mode in {"vector_2d_lookahead", "vector_2d_damped"} else None
        ),
        "desired_yaw_delta_deg": yaw_delta,
        "unconstrained_turn_command_deg": unconstrained_turn,
        "speed_saturated": speed_sat,
        "turn_saturated": turn_sat,
        "speed_model": speed_model,
        "measured_forward_velocity_mps": float(current_forward_velocity),
        "adaptive_speed_model": (
            {
                "a": float(adaptive_speed_model.theta[0]),
                "b": float(adaptive_speed_model.theta[1]),
                "c": float(adaptive_speed_model.theta[2]),
                "samples": int(adaptive_speed_model.samples),
            }
            if adaptive_speed_model is not None
            else None
        ),
    }


def drone_control(
    actual: list[float], previous_actual: list[float] | None, reference: list[float], dt: float, args: argparse.Namespace
) -> tuple[list[float], dict[str, Any]]:
    desired_velocity = reference_velocity(actual, reference, dt)
    measured_velocity = np.zeros(2, dtype=float) if previous_actual is None else body_xy_velocity(previous_actual, actual, dt)
    a_xy = np.asarray([args.drone_a_forward, args.drone_a_lateral], dtype=float)
    b_xy = np.asarray([args.drone_b_forward, args.drone_b_lateral], dtype=float)
    unconstrained_velocity_command = (desired_velocity - a_xy * measured_velocity) / np.maximum(b_xy, 1e-6)
    command_velocity = np.empty(2, dtype=float)
    saturation = []
    for axis in range(2):
        command_velocity[axis], clipped = clamp(unconstrained_velocity_command[axis], args.drone_max_command_mps)
        saturation.append(clipped)

    omega_measured = 0.0
    if previous_actual is not None:
        omega_measured = math.radians(wrap_deg(float(actual[4]) - float(previous_actual[4]))) / dt
    omega_desired = math.radians(wrap_deg(float(reference[4]) - float(actual[4]))) / dt
    yaw_unconstrained = (omega_desired - args.drone_yaw_a * omega_measured) / max(args.drone_yaw_b, 1e-6)
    yaw_command, yaw_sat = clamp(yaw_unconstrained, args.drone_max_yaw_command_radps)
    action = [float(command_velocity[0] * dt), float(command_velocity[1] * dt), 0.0, float(yaw_command)]
    predicted_velocity = a_xy * measured_velocity + b_xy * command_velocity
    return action, {
        "desired_body_velocity_mps": desired_velocity.tolist(),
        "measured_body_velocity_mps": measured_velocity.tolist(),
        "unconstrained_body_velocity_command_mps": unconstrained_velocity_command.tolist(),
        "commanded_body_velocity_mps": command_velocity.tolist(),
        "predicted_next_body_velocity_mps": predicted_velocity.tolist(),
        "desired_yaw_rate_radps": omega_desired,
        "measured_yaw_rate_radps": omega_measured,
        "unconstrained_yaw_command_radps": yaw_unconstrained,
        "yaw_command_radps": yaw_command,
        "translation_saturated": saturation,
        "yaw_saturated": yaw_sat,
        "z_reference_error_m": float((reference[2] - actual[2]) / UNREAL_UNITS_PER_METER),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--recorded-dir", type=Path, required=True)
    parser.add_argument("--episode", default="0")
    parser.add_argument("--env-id", default="UnrealTrack-Demonstration_Castle-ContinuousColor-v0")
    parser.add_argument("--save-dir", type=Path, required=True)
    parser.add_argument("--dt", type=float, default=0.1)
    parser.add_argument("--ue-interval-ms", type=int, default=100)
    parser.add_argument("--max-steps", type=int, default=0)
    parser.add_argument("--seed", type=int, default=100)
    parser.add_argument("--render-gpu", type=int, default=2)
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=480)
    parser.add_argument("--drone-camera-pitch", type=float, default=None)
    parser.add_argument("--drone-camera-yaw-offset", type=float, default=None)
    parser.add_argument("--robotdog-camera-pitch", type=float, default=None)
    parser.add_argument("--robotdog-camera-yaw-offset", type=float, default=None)
    parser.add_argument("--robotdog-camera-mount", type=float, nargs=3, default=None, metavar=("X", "Y", "Z"))
    parser.add_argument("--offscreen", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--launch-retries", type=int, default=5)
    parser.add_argument(
        "--snapshot-retries",
        type=int,
        default=8,
        help="Retries for transient/incomplete UnrealCV snapshots before restarting the episode.",
    )
    parser.add_argument(
        "--snapshot-mode",
        choices=("sequential", "batch"),
        default="sequential",
        help="Use sequential requests for stability (default); batch is retained only for compatibility/benchmarking.",
    )
    parser.add_argument(
        "--snapshot-render-sync-s",
        type=float,
        default=0.08,
        help="GPU/render-thread settling interval between sequential RGB/mask readbacks.",
    )
    parser.add_argument(
        "--visual-label-mode",
        choices=("source_recording", "replay_mask"),
        default="replay_mask",
        help=(
            "Use source-recorded bbox/visibility labels without requesting object masks (stable default), "
            "or render fresh replay masks (slower and unstable on some UE5.6 maps)."
        ),
    )
    parser.add_argument(
        "--post-reset-settle-s",
        type=float,
        default=3.0,
        help="Seconds to let UE finish map/proxy-annotation rendering before the first camera request.",
    )
    parser.add_argument("--human-appearance-id", type=int, default=5)
    parser.add_argument("--robotdog-appearance-id", type=int, default=27)
    parser.add_argument("--ground-acceleration", type=float, default=10000.0)
    parser.add_argument("--ground-turn-step-gain", type=float, default=0.4)
    parser.add_argument("--ground-max-turn-deg", type=float, default=30.0)
    parser.add_argument("--human-max-speed-mps", type=float, default=1.2)
    parser.add_argument("--dog-max-speed-mps", type=float, default=1.4)
    parser.add_argument("--ground-translation-delay-steps", type=int, choices=(0, 1), default=1)
    parser.add_argument("--ground-position-feedback-time-s", type=float, default=1.0)
    parser.add_argument(
        "--ground-max-forward-feedback-mps",
        type=float,
        default=float("inf"),
        help="Clamp only the executable forward position-feedback term; infinity preserves legacy behavior.",
    )
    parser.add_argument(
        "--ground-speed-model",
        choices=("legacy_preview", "adaptive_inverse"),
        default="legacy_preview",
        help="adaptive_inverse estimates the delayed forward-speed response online while preserving source yaw.",
    )
    parser.add_argument(
        "--ground-control-mode",
        choices=("source_yaw", "vector_2d", "vector_2d_stable", "vector_2d_lookahead", "vector_2d_damped"),
        default="source_yaw",
        help="source_yaw strictly restores source heading; vector_2d steers toward the desired XY velocity vector; vector_2d_stable uses bounded heading and reverse speed; vector_2d_lookahead uses a spatial heading target; vector_2d_damped also rate-limits its heading goal and slows during turns.",
    )
    parser.add_argument("--ground-vector-min-speed-mps", type=float, default=0.12)
    parser.add_argument("--ground-vector-max-heading-delta-deg", type=float, default=20.0)
    parser.add_argument("--ground-heading-lookahead-steps", type=int, default=6)
    parser.add_argument("--ground-reverse-enter-deg", type=float, default=110.0)
    parser.add_argument("--ground-reverse-exit-deg", type=float, default=70.0)
    parser.add_argument("--ground-heading-goal-rate-deg", type=float, default=3.0)
    parser.add_argument("--ground-turn-slowdown-floor", type=float, default=0.25)
    parser.add_argument("--ground-heading-deadband-deg", type=float, default=1.5)
    parser.add_argument("--drone-a-forward", type=float, default=0.969)
    parser.add_argument("--drone-b-forward", type=float, default=0.0301)
    parser.add_argument("--drone-a-lateral", type=float, default=0.969)
    parser.add_argument("--drone-b-lateral", type=float, default=0.0301)
    parser.add_argument("--drone-yaw-a", type=float, default=0.464)
    parser.add_argument("--drone-yaw-b", type=float, default=0.359)
    parser.add_argument("--drone-max-command-mps", type=float, default=1.5)
    parser.add_argument("--drone-max-speed-mps", type=float, default=None)
    parser.add_argument("--drone-max-yaw-command-radps", type=float, default=0.7)
    parser.add_argument("--save-video", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--write-global-video", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument(
        "--write-training-records",
        action=argparse.BooleanOptionalAction,
        default=False,
        help="Write standard *_drone_info.json/*_robotdog_info.json with replay RGB-mask observations and realized labels.",
    )
    parser.add_argument(
        "--training-waypoint-horizon",
        type=int,
        default=10,
        help="Number of future 0.1s replay poses saved in actual_waypoints diagnostics.",
    )
    return parser.parse_args()


def _require(rows: list[dict[str, Any]], index: int, key: str) -> list[float]:
    pose = valid_pose(rows[index].get(key))
    if pose is None:
        raise ValueError(f"source step {index + 1} has no valid {key}")
    return pose


def _reference(rows: list[dict[str, Any]], index: int, key: str) -> list[float]:
    return next_or_after(rows, index, key)


def plot_results(rows: list[dict[str, Any]], output: Path) -> None:
    """Small dependency-free-enough diagnostic plot, generated after the run."""
    try:
        import matplotlib.pyplot as plt
    except Exception as exc:
        print(f"[plot] unavailable: {exc}", flush=True)
        return
    t = np.asarray([r["step"] for r in rows], dtype=float) * float(rows[0]["dt"])
    fig, axes = plt.subplots(2, 2, figsize=(12, 8), constrained_layout=True)
    for name, color in (("target", "tab:green"), ("robotdog", "tab:orange"), ("drone", "tab:blue")):
        reference = np.asarray([r[f"source_{name}_pose_after_action"][:2] for r in rows], dtype=float) / UNREAL_UNITS_PER_METER
        actual = np.asarray([r[f"{name}_pose_after_action"][:2] for r in rows], dtype=float) / UNREAL_UNITS_PER_METER
        axes[0, 0].plot(reference[:, 0], reference[:, 1], "--", color=color, alpha=.65, label=f"{name} source")
        axes[0, 0].plot(actual[:, 0], actual[:, 1], color=color, label=f"{name} replay")
        axes[0, 1].plot(t, [r[f"{name}_after_error_m"] for r in rows], color=color, label=name)
        axes[1, 0].plot(t, [r[f"{name}_yaw_after_error_deg"] for r in rows], color=color, label=name)
    axes[1, 1].plot(t, [int(any(r["drone_inverse"]["translation_saturated"])) for r in rows], label="drone translation sat")
    axes[1, 1].plot(t, [int(r["drone_inverse"]["yaw_saturated"]) for r in rows], label="drone yaw sat")
    axes[1, 1].plot(t, [int(r["target_inverse"]["speed_saturated"] or r["target_inverse"]["turn_saturated"]) for r in rows], label="human saturation")
    axes[1, 1].plot(t, [int(r["robotdog_inverse"]["speed_saturated"] or r["robotdog_inverse"]["turn_saturated"]) for r in rows], label="dog saturation")
    axes[0, 0].set(xlabel="world x (m)", ylabel="world y (m)", title="source vs replay trajectory")
    axes[0, 1].set(xlabel="time (s)", ylabel="3D error (m)", title="after-action position error")
    axes[1, 0].set(xlabel="time (s)", ylabel="yaw error (deg)", title="after-action yaw error")
    axes[1, 1].set(xlabel="time (s)", ylabel="saturated (0/1)", title="inverse command saturation")
    for axis in axes.flat:
        axis.grid(True, alpha=.25)
        axis.legend(fontsize=8)
    fig.savefig(output, dpi=150)
    plt.close(fig)


def bbox_center_metrics(bbox: list[int], width: int, height: int) -> tuple[float, bool]:
    """Return normalized center error and a conservative centered flag."""
    if len(bbox) < 4 or int(bbox[2]) <= 0 or int(bbox[3]) <= 0:
        return 1.0, False
    cx = float(bbox[0]) + 0.5 * float(bbox[2])
    cy = float(bbox[1]) + 0.5 * float(bbox[3])
    error = math.hypot(cx - 0.5 * width, cy - 0.5 * height) / max(math.hypot(width, height), 1.0)
    return float(error), bool(error <= 0.15)


def xy_distance_m(first: list[float], second: list[float]) -> float:
    return float(np.linalg.norm(np.asarray(first[:2], dtype=float) - np.asarray(second[:2], dtype=float)) / UNREAL_UNITS_PER_METER)


def write_training_records(
    output_dir: Path,
    episode: str,
    rows: list[dict[str, Any]],
    args: argparse.Namespace,
    instruction: str,
) -> None:
    """Emit the exact multi-agent recording contract consumed by make_tracking_data.

    ``base_velocity`` intentionally means *measured replay response*, while
    ``commanded_base_velocity`` and ``env_action`` retain the inverse command.
    This prevents the trainer from silently learning an infeasible command as
    though it were a realized motion.
    """
    if not rows:
        return
    drone_pitch = float(args.drone_camera_pitch) if args.drone_camera_pitch is not None else float(rows[0].get("drone_camera_pitch", -40.0))
    drone_yaw_offset = float(args.drone_camera_yaw_offset) if args.drone_camera_yaw_offset is not None else float(rows[0].get("drone_camera_yaw_offset", 0.0))
    dog_pitch = float(args.robotdog_camera_pitch) if args.robotdog_camera_pitch is not None else float(rows[0].get("robotdog_camera_pitch", -8.0))
    dog_yaw_offset = float(args.robotdog_camera_yaw_offset) if args.robotdog_camera_yaw_offset is not None else float(rows[0].get("robotdog_camera_yaw_offset", 0.0))
    dog_mount = list(args.robotdog_camera_mount) if args.robotdog_camera_mount is not None else [140.0, 0.0, 110.0]
    pose_after = {
        "drone": [row["drone_pose_after_action"] for row in rows],
        "robotdog": [row["robotdog_pose_after_action"] for row in rows],
    }
    infos: dict[str, list[dict[str, Any]]] = {"drone": [], "robotdog": []}
    for index, row in enumerate(rows):
        for agent in ("drone", "robotdog"):
            pose_key = f"{agent}_pose"
            after_key = f"{agent}_pose_after_action"
            bbox_prefix = agent
            bbox = [int(value) for value in row[f"{bbox_prefix}_target_bbox"]]
            center_error, centered = bbox_center_metrics(bbox, int(args.width), int(args.height))
            actual_velocity = realized_base_velocity(row[pose_key], row[after_key], args.dt)
            if agent == "drone":
                action = [float(value) for value in row["drone_env_action"]]
                commanded_velocity = [action[0] / args.dt, action[1] / args.dt, action[3]]
            else:
                action = [float(value) for value in row["robotdog_env_action"]]
                # Ground turn command has the measured BP scale relation
                # delta_yaw_deg = ground_turn_step_gain * command_deg.
                commanded_velocity = [
                    action[1] / UNREAL_UNITS_PER_METER,
                    0.0,
                    math.radians(args.ground_turn_step_gain * action[0]) / args.dt,
                ]
            waypoints, waypoint_mask = local_waypoints(
                pose_after[agent], index, args.training_waypoint_horizon
            )
            info = {
                "step": int(row["step"]),
                "dt": float(args.dt),
                "effective_dt_s": float(args.dt),
                "training_dt_s": float(args.dt),
                "fixed_timestep_seconds": float(args.dt),
                "observation_timestamp_s": float(index * args.dt),
                pose_key: row[pose_key],
                after_key: row[after_key],
                "target_pose": row["target_pose"],
                "target_pose_after_action": row["target_pose_after_action"],
                "target_bbox": bbox,
                "target_visible": bool(row[f"{bbox_prefix}_target_visible"]),
                "target_visibility": float(row[f"{bbox_prefix}_target_visibility"]),
                "target_center_error": center_error,
                "target_centered": centered,
                "target_bbox_source": row.get(f"{agent}_target_bbox_source", "replay_object_mask"),
                "drone_camera_pitch": drone_pitch,
                "drone_camera_yaw_offset": drone_yaw_offset,
                "robotdog_camera_pitch": dog_pitch,
                "robotdog_camera_yaw_offset": dog_yaw_offset,
                "robotdog_camera_mount": dog_mount,
                "dis_to_human": xy_distance_m(row[pose_key], row["target_pose"]),
                "base_velocity": actual_velocity,
                "commanded_base_velocity": commanded_velocity,
                "env_action": action,
                "command_label_source": "uncapped_inverse_fixed_dt_realized",
                "actual_waypoints": waypoints,
                "actual_waypoint_valid_mask": waypoint_mask,
                "actual_waypoint_dt_s": float(args.dt),
                "source_after_error_m": float(row[f"{agent}_after_error_m"]),
                "source_yaw_after_error_deg": float(row[f"{agent}_yaw_after_error_deg"]),
                "collision": False,
                "instruction": instruction,
            }
            if agent == "drone":
                info["drone_action"] = action
            else:
                info["ground_action"] = action
            infos[agent].append(info)
    write_json(output_dir / f"{episode}_drone_info.json", infos["drone"])
    write_json(output_dir / f"{episode}_robotdog_info.json", infos["robotdog"])
    stat = {
        "finish": True,
        "status": "ReplayComplete",
        "success": 1.0,
        "total_step": len(rows),
        "collision": 0.0,
        "instruction": instruction,
        "dt": float(args.dt),
        "training_dt_s": float(args.dt),
        "video_fps": int(round(1.0 / args.dt)),
        "obs_action_alignment": "obs_t_action_t",
        "label_source": "uncapped_inverse_fixed_dt_realized",
        "drone_camera_pitch": drone_pitch,
        "drone_camera_yaw_offset": drone_yaw_offset,
        "robotdog_camera_pitch": dog_pitch,
        "robotdog_camera_yaw_offset": dog_yaw_offset,
        "robotdog_camera_mount": dog_mount,
        "all_steps_retained": True,
        "drone_following_rate": float(np.mean([bool(row["drone_target_visible"]) for row in rows])),
        "robotdog_following_rate": float(np.mean([bool(row["robotdog_target_visible"]) for row in rows])),
    }
    write_json(output_dir / f"{episode}.json", stat)


def main() -> int:
    args = parse_args()
    if args.write_training_records and args.visual_label_mode != "replay_mask":
        raise ValueError(
            "training records require --visual-label-mode replay_mask; "
            "source-recorded boxes are not exact for replay RGB"
        )
    if args.dt <= 0 or args.ue_interval_ms != int(round(args.dt * 1000.0)):
        raise ValueError("fixed replay requires --dt > 0 and --ue-interval-ms = dt * 1000")
    if args.ground_max_forward_feedback_mps < 0:
        raise ValueError("--ground-max-forward-feedback-mps must be non-negative")
    if min(args.drone_b_forward, args.drone_b_lateral, args.drone_yaw_b) <= 0:
        raise ValueError("inverse model b coefficients must be positive")
    if args.training_waypoint_horizon < 1:
        raise ValueError("--training-waypoint-horizon must be positive")
    if args.post_reset_settle_s < 0:
        raise ValueError("--post-reset-settle-s must be non-negative")
    os.environ["UNREALZOO_FIXED_TIMESTEP"] = f"{args.dt:.9g}"
    random.seed(args.seed)
    np.random.seed(args.seed)
    source = args.recorded_dir.expanduser().resolve()
    drone_path, dog_path, stat_path = source / f"{args.episode}_drone_info.json", source / f"{args.episode}_robotdog_info.json", source / f"{args.episode}.json"
    drone_rows, dog_rows = read_json(drone_path), read_json(dog_path)
    stat = read_json(stat_path) if stat_path.is_file() else None
    if not isinstance(drone_rows, list) or not isinstance(dog_rows, list):
        raise ValueError("source drone/dog files must be JSON arrays")
    count = min(len(drone_rows), len(dog_rows))
    if args.max_steps > 0:
        count = min(count, args.max_steps)
    if count < 1:
        raise ValueError("no source steps")
    args.save_dir.mkdir(parents=True, exist_ok=True)
    env_args = build_env_args(args, drone_rows[0], stat if isinstance(stat, dict) else None)
    if args.drone_max_speed_mps is not None:
        env_args.drone_max_speed = float(args.drone_max_speed_mps)
    env_args.top_view_height = None
    config = vars(args).copy()
    config.update({"protocol": "fixed_dt_closed_loop_inverse_dynamics", "source_dir": str(source), "no_per_step_pose_restore": True, "ground_yaw_relation": "delta_yaw_deg = 0.4 * turn_command_deg", "ground_translation_model": "speed[t] affects translation[t+1] when ground_translation_delay_steps=1", "ground_control_mode": args.ground_control_mode, "drone_translation_model": "v_next = a*v_current + b*u (empirical action delay=0)", "drone_yaw_model": "omega_next = a*omega_current + b*u (empirical action delay=0)", "training_record_labels": "realized replay base_velocity; env_action is the exact command supplied to UE", "all_steps_retained": True})
    config["recorded_dir"] = str(source)
    config["save_dir"] = str(args.save_dir)
    write_json(args.save_dir / "replay_config.json", config)
    print(f"[inverse] source={source} episode={args.episode} steps={count} dt={args.dt:.3f}s gpu={args.render_gpu}", flush=True)

    env = make_env(env_args)
    writers: dict[str, cv2.VideoWriter] = {}
    replay_rows: list[dict[str, Any]] = []
    try:
        reset_env(env, env_args)
        # Reset triggers a large asynchronous ProxyAnnotator render pass. A
        # first RGB/mask request during that pass can crash UE's rendering
        # thread on Vulkan; keep the simulator idle until it settles.
        if args.post_reset_settle_s > 0:
            print(f"[reset] settling UE for {args.post_reset_settle_s:.1f}s before camera setup", flush=True)
            time.sleep(float(args.post_reset_settle_s))
        target_id, dog_id, drone_id = classify_coop_agents(env)
        players = env.unwrapped.player_list
        target_name, dog_name, drone_name = players[target_id], players[dog_id], players[drone_id]
        env.unwrapped.unrealcv.set_appearance(target_name, args.human_appearance_id)
        env.unwrapped.unrealcv.set_appearance(dog_name, args.robotdog_appearance_id)
        first_target, first_dog, first_drone = _require(drone_rows, 0, "target_pose"), _require(dog_rows, 0, "robotdog_pose"), _require(drone_rows, 0, "drone_pose")
        restore_pose(env, target_name, first_target)
        restore_pose(env, dog_name, first_dog, lambda yaw: set_ground_yaw(env, dog_name, yaw))
        restore_pose(env, drone_name, first_drone, lambda yaw: maybe_set_drone_yaw(env, drone_name, yaw))
        first_dog_row, first_drone_row = dog_rows[0], drone_rows[0]
        dog_mount = list(args.robotdog_camera_mount) if args.robotdog_camera_mount is not None else [float(v) for v in first_dog_row.get("robotdog_camera_mount", [140, 0, 110])[:3]]
        dog_pitch = float(args.robotdog_camera_pitch) if args.robotdog_camera_pitch is not None else float(first_dog_row.get("robotdog_camera_pitch", -15.0))
        dog_yaw_offset = float(args.robotdog_camera_yaw_offset) if args.robotdog_camera_yaw_offset is not None else float(first_dog_row.get("robotdog_camera_yaw_offset", 0.0))
        drone_pitch = float(args.drone_camera_pitch) if args.drone_camera_pitch is not None else float(first_drone_row.get("drone_camera_pitch", -40.0))
        drone_yaw_offset = float(args.drone_camera_yaw_offset) if args.drone_camera_yaw_offset is not None else float(first_drone_row.get("drone_camera_yaw_offset", 0.0))
        set_robotdog_camera(env, dog_name, dog_id, dog_mount, dog_pitch, dog_yaw_offset, dog_args(env_args))
        set_drone_camera(env, drone_name, drone_id, first_drone, drone_pitch, drone_yaw_offset, drone_args(env_args))
        unrealcv = env.unwrapped.unrealcv
        unrealcv.set_global_time_dilation(1.0)
        unrealcv.set_max_FPS(1.0 / args.dt)
        unrealcv.set_pause()
        if args.visual_label_mode == "replay_mask":
            response = unrealcv.client.request("vrun r.FinishCurrentFrame 1")
            if response is None:
                raise RuntimeError("failed to enable r.FinishCurrentFrame for exact replay masks")
        for name, speed in ((target_name, args.human_max_speed_mps), (dog_name, args.dog_max_speed_mps)):
            unrealcv.set_max_speed(name, float(speed * UNREAL_UNITS_PER_METER))
            unrealcv.set_acceleration(name, float(args.ground_acceleration))
        # Restore again behind the pause barrier. This is deliberately the final restore.
        restore_pose(env, target_name, first_target)
        restore_pose(env, dog_name, first_dog, lambda yaw: set_ground_yaw(env, dog_name, yaw))
        restore_pose(env, drone_name, first_drone, lambda yaw: maybe_set_drone_yaw(env, drone_name, yaw))
        refresh_poses(env)
        previous_actual: dict[str, list[float] | None] = {"target": None, "robotdog": None, "drone": None}
        ground_reverse_mode = {"target": False, "robotdog": False}
        ground_heading_goal: dict[str, float | None] = {"target": None, "robotdog": None}
        ground_speed_models = {"target": AdaptiveGroundSpeedModel(), "robotdog": AdaptiveGroundSpeedModel()}
        paths = {"drone": args.save_dir / f"{args.episode}_drone.mp4", "robotdog": args.save_dir / f"{args.episode}_robotdog.mp4", "global": args.save_dir / f"{args.episode}_global.mp4"}

        for index in range(count):
            before = refresh_poses(env)
            actual_target, actual_dog, actual_drone = list(before[target_id]), list(before[dog_id]), list(before[drone_id])
            target_forward_velocity = (
                float(body_xy_velocity(previous_actual["target"], actual_target, args.dt)[0])
                if previous_actual["target"] is not None
                else 0.0
            )
            dog_forward_velocity = (
                float(body_xy_velocity(previous_actual["robotdog"], actual_dog, args.dt)[0])
                if previous_actual["robotdog"] is not None
                else 0.0
            )
            if args.ground_speed_model == "adaptive_inverse":
                ground_speed_models["target"].update(target_forward_velocity)
                ground_speed_models["robotdog"].update(dog_forward_velocity)
            source_target_before, source_dog_before = _require(drone_rows, index, "target_pose"), _require(dog_rows, index, "robotdog_pose")
            reference_target, reference_dog, reference_drone = _reference(drone_rows, index, "target_pose"), _reference(dog_rows, index, "robotdog_pose"), _reference(drone_rows, index, "drone_pose")
            reference_target_next = _reference(drone_rows, index + 1, "target_pose") if index + 1 < count else reference_target
            reference_dog_next = _reference(dog_rows, index + 1, "robotdog_pose") if index + 1 < count else reference_dog
            lookahead_index = min(index + max(1, args.ground_heading_lookahead_steps), count - 1)
            reference_target_lookahead = _reference(drone_rows, lookahead_index, "target_pose")
            reference_dog_lookahead = _reference(dog_rows, lookahead_index, "robotdog_pose")
            target_action, target_info = ground_control(
                actual_target, source_target_before, reference_target, reference_target_next, args.dt,
                args.ground_turn_step_gain, args.human_max_speed_mps, args.ground_max_turn_deg,
                args.ground_translation_delay_steps, args.ground_position_feedback_time_s, args.ground_control_mode,
                args.ground_vector_min_speed_mps, args.ground_vector_max_heading_delta_deg,
                reference_target_lookahead, ground_reverse_mode["target"], args.ground_reverse_enter_deg,
                args.ground_reverse_exit_deg, ground_heading_goal["target"], args.ground_heading_goal_rate_deg,
                args.ground_turn_slowdown_floor, args.ground_heading_deadband_deg,
                args.ground_max_forward_feedback_mps,
                args.ground_speed_model,
                ground_speed_models["target"] if args.ground_speed_model == "adaptive_inverse" else None,
                target_forward_velocity,
            )
            dog_action, dog_info = ground_control(
                actual_dog, source_dog_before, reference_dog, reference_dog_next, args.dt,
                args.ground_turn_step_gain, args.dog_max_speed_mps, args.ground_max_turn_deg,
                args.ground_translation_delay_steps, args.ground_position_feedback_time_s, args.ground_control_mode,
                args.ground_vector_min_speed_mps, args.ground_vector_max_heading_delta_deg,
                reference_dog_lookahead, ground_reverse_mode["robotdog"], args.ground_reverse_enter_deg,
                args.ground_reverse_exit_deg, ground_heading_goal["robotdog"], args.ground_heading_goal_rate_deg,
                args.ground_turn_slowdown_floor, args.ground_heading_deadband_deg,
                args.ground_max_forward_feedback_mps,
                args.ground_speed_model,
                ground_speed_models["robotdog"] if args.ground_speed_model == "adaptive_inverse" else None,
                dog_forward_velocity,
            )
            ground_reverse_mode["target"] = bool(target_info["reverse_mode"])
            ground_reverse_mode["robotdog"] = bool(dog_info["reverse_mode"])
            ground_heading_goal["target"] = target_info["heading_goal_deg"]
            ground_heading_goal["robotdog"] = dog_info["heading_goal_deg"]
            if args.ground_speed_model == "adaptive_inverse":
                ground_speed_models["target"].set_command(float(target_action[1]) / UNREAL_UNITS_PER_METER)
                ground_speed_models["robotdog"].set_command(float(dog_action[1]) / UNREAL_UNITS_PER_METER)
            drone_action, drone_info = drone_control(actual_drone, previous_actual["drone"], reference_drone, args.dt, args)
            # Observations are captured while UE is paused, before action t.
            # UE5.6's object-mask render pass can crash the Vulkan rendering
            # thread on some maps.  Source recordings already contain bbox
            # and visibility labels, so use them by default while preserving
            # replay RGB/video and all dynamics metrics.
            observation = None
            masks: list[np.ndarray | None] | None = None
            drone_visibility, drone_visible, drone_bbox = 0.0, False, [0, 0, 0, 0]
            dog_visibility, dog_visible, dog_bbox = 0.0, False, [0, 0, 0, 0]
            if args.save_video or args.write_training_records:
                set_robotdog_camera(env, dog_name, dog_id, dog_mount, dog_pitch, dog_yaw_offset, dog_args(env_args))
                set_drone_camera(env, drone_name, drone_id, actual_drone, drone_pitch, drone_yaw_offset, drone_args(env_args))
                observation, masks = capture_color_mask_snapshot_stable(
                    env,
                    include_masks=args.write_training_records and args.visual_label_mode == "replay_mask",
                    attempts=args.snapshot_retries,
                    mode=args.snapshot_mode,
                    render_sync_s=args.snapshot_render_sync_s if args.visual_label_mode == "replay_mask" else 0.0,
                )
                if args.write_training_records:
                    if args.visual_label_mode == "replay_mask":
                        drone_visibility, drone_visible, drone_bbox = object_mask_ratio_and_bbox(
                            env, env.unwrapped.cam_list[drone_id], target_name, mask_img=masks[drone_id]
                        )
                        dog_visibility, dog_visible, dog_bbox = object_mask_ratio_and_bbox(
                            env, env.unwrapped.cam_list[dog_id], target_name, mask_img=masks[dog_id]
                        )
                    else:
                        drone_visual = drone_rows[index]
                        dog_visual = dog_rows[index]
                        drone_bbox = list(drone_visual.get("target_bbox", [0, 0, 0, 0]))
                        dog_bbox = list(dog_visual.get("target_bbox", [0, 0, 0, 0]))
                        drone_visibility = float(drone_visual.get("target_visibility", 0.0))
                        dog_visibility = float(dog_visual.get("target_visibility", 0.0))
                        drone_visible = bool(drone_visual.get("target_visible", False))
                        dog_visible = bool(dog_visual.get("target_visible", False))
            if args.save_video:
                if observation is None:
                    raise RuntimeError("video requested but no paused observation was captured")
                write_video_frame(writers, "drone", paths["drone"], observation[drone_id], 1.0 / args.dt)
                write_video_frame(writers, "robotdog", paths["robotdog"], observation[dog_id], 1.0 / args.dt)
                if args.write_global_video:
                    frame = get_global_frame(env, env_args, actual_target, actual_dog, actual_drone)
                    if frame is not None:
                        write_video_frame(writers, "global", paths["global"], frame, 1.0 / args.dt)
            actions: list[list[float] | None] = [None] * len(players)
            actions[target_id], actions[dog_id], actions[drone_id] = target_action, dog_action, drone_action
            after, pulse = fixed_step(env, actions)
            after_target, after_dog, after_drone = list(after[target_id]), list(after[dog_id]), list(after[drone_id])
            row = {
                "step": index + 1, "dt": args.dt, "pulse_wall_time_s": pulse,
                "target_pose": actual_target, "target_pose_after_action": after_target, "source_target_pose_after_action": reference_target,
                "robotdog_pose": actual_dog, "robotdog_pose_after_action": after_dog, "source_robotdog_pose_after_action": reference_dog,
                "drone_pose": actual_drone, "drone_pose_after_action": after_drone, "source_drone_pose_after_action": reference_drone,
                "target_env_action": target_action, "robotdog_env_action": dog_action, "drone_env_action": drone_action,
                "target_inverse": target_info, "robotdog_inverse": dog_info, "drone_inverse": drone_info,
                "drone_target_bbox": drone_bbox, "drone_target_visible": drone_visible, "drone_target_visibility": drone_visibility,
                "robotdog_target_bbox": dog_bbox, "robotdog_target_visible": dog_visible, "robotdog_target_visibility": dog_visibility,
                "drone_target_bbox_source": "replay_object_mask" if args.visual_label_mode == "replay_mask" else "source_recording",
                "robotdog_target_bbox_source": "replay_object_mask" if args.visual_label_mode == "replay_mask" else "source_recording",
                "target_after_error_m": pose_error_m(after_target, reference_target), "robotdog_after_error_m": pose_error_m(after_dog, reference_dog), "drone_after_error_m": pose_error_m(after_drone, reference_drone),
                "target_yaw_after_error_deg": yaw_error_deg(after_target, reference_target), "robotdog_yaw_after_error_deg": yaw_error_deg(after_dog, reference_dog), "drone_yaw_after_error_deg": yaw_error_deg(after_drone, reference_drone),
            }
            replay_rows.append(row)
            previous_actual.update({"target": actual_target, "robotdog": actual_dog, "drone": actual_drone})
            if index < 5 or (index + 1) % 25 == 0:
                print(f"[step {index + 1}] target={row['target_after_error_m']:.3f}m dog={row['robotdog_after_error_m']:.3f}m drone={row['drone_after_error_m']:.3f}m sat=({int(any(drone_info['translation_saturated']))},{int(drone_info['yaw_saturated'])})", flush=True)
    finally:
        for writer in writers.values():
            writer.release()
        try:
            env.close()
        except Exception:
            pass

    metric = lambda key: np.asarray([float(row[key]) for row in replay_rows], dtype=float)
    summary = {"protocol": "fixed_dt_closed_loop_inverse_dynamics", "source_dir": str(source), "episode": str(args.episode), "steps": len(replay_rows), "dt": args.dt}
    for agent in ("target", "robotdog", "drone"):
        for key, label in ((f"{agent}_after_error_m", "position"), (f"{agent}_yaw_after_error_deg", "yaw")):
            values = metric(key)
            summary[f"{agent}_{label}_error"] = {"mean": float(values.mean()), "p95": float(np.quantile(values, .95)), "max": float(values.max())}
    summary["saturation_rate"] = {
        "target": float(np.mean([r["target_inverse"]["speed_saturated"] or r["target_inverse"]["turn_saturated"] for r in replay_rows])),
        "robotdog": float(np.mean([r["robotdog_inverse"]["speed_saturated"] or r["robotdog_inverse"]["turn_saturated"] for r in replay_rows])),
        "drone_translation": float(np.mean([any(r["drone_inverse"]["translation_saturated"]) for r in replay_rows])),
        "drone_yaw": float(np.mean([r["drone_inverse"]["yaw_saturated"] for r in replay_rows])),
    }
    write_json(args.save_dir / f"{args.episode}_inverse_replay.json", replay_rows)
    write_json(args.save_dir / "summary.json", summary)
    if args.write_training_records:
        source_instruction = (
            str(stat.get("instruction"))
            if isinstance(stat, dict) and stat.get("instruction")
            else "Track the person collaboratively while keeping them visible."
        )
        write_training_records(args.save_dir, str(args.episode), replay_rows, args, source_instruction)
    csv_path = args.save_dir / f"{args.episode}_step_metrics.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        fields = ["step", "target_after_error_m", "robotdog_after_error_m", "drone_after_error_m", "target_yaw_after_error_deg", "robotdog_yaw_after_error_deg", "drone_yaw_after_error_deg", "pulse_wall_time_s"]
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows([{key: row[key] for key in fields} for row in replay_rows])
    plot_results(replay_rows, args.save_dir / "trajectory_error_saturation.png")
    print(json.dumps(summary, ensure_ascii=False, indent=2), flush=True)
    print(f"[done] output={args.save_dir}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
